name: "Android CI - Sip&Savour"

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # CORRECTION ICI : On précise le dossier de travail
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./app  # Indispensable car gradlew est dans le dossier 'app'

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: ./app  # Idem ici

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
        working-directory: ./app  # Et ici
